<?php /** @var \Fc\Faqs\Block\FaqsList $block */ ?>
<h1><?php echo __('Frequently Asked Questions') ?></h1>
<div id="faqs-faq-list">
    <?php /** @var \Fc\Faqs\Model\Faq $faq */ ?>
    <?php foreach ($block->getFaqs() as $faq): ?>
        <div data-role="collapsible">
            <div data-role="trigger">
                <h3 class="faqs-faq-item-title"><?php echo $faq->getTitle() ?></h3>
            </div>
        </div>
        <div data-role="content" class="faq-item-content">
            <?php echo $faq->getContent(); ?>
            <div class="faq-item-meta">
                <strong><?php echo __('Created at:') ?></strong> <?php echo $faq->getCreationTime() ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<script>
    require(['jquery', 'tabs'], function ($) {
        $("#faqs-faq-list").accordion();
    });
</script>
